export const doctors = [
  {
    name: "Dr. John Doe",
    specialty: "Dentist",
    yearsOfExperience: 10,
    description: "Expert in dental implants.",
    rating: 4.8,
    sessions: 120,
    interests: ["Dental Implants", "Teeth Whitening", "Smile Makeover"],
    appointment: "Saturday, Dec. 21 at 09:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Jane Smith",
    specialty: "Dentist",
    yearsOfExperience: 8,
    description: "Specialist in cosmetic dentistry.",
    rating: 4.7,
    sessions: 100,
    interests: ["Cosmetic Dentistry", "Teeth Whitening", "Dental Bonding"],
    appointment: "Sunday, Dec. 22 at 10:30 AM",
    topRated: true,
  },
  {
    name: "Dr. Emily Johnson",
    specialty: "Dentist",
    yearsOfExperience: 12,
    description: "Specializes in orthodontics.",
    rating: 4.9,
    sessions: 150,
    interests: ["Braces", "Invisalign", "Clear Aligners", "Jaw Alignment"],
    appointment: "Monday, Dec. 23 at 02:15 PM",
    topRated: true,
  },
  {
    name: "Dr. Michael Brown",
    specialty: "Dentist",
    yearsOfExperience: 15,
    description: "Expert in oral surgery.",
    rating: 4.6,
    sessions: 200,
    interests: ["Oral Surgery", "Wisdom Teeth Removal", "Dental Implants"],
    appointment: "Tuesday, Dec. 24 at 11:45 AM",
    topRated: false,
  },
  {
    name: "Dr. Sarah Davis",
    specialty: "Dentist",
    yearsOfExperience: 7,
    description: "Specialist in pediatric dentistry.",
    rating: 4.8,
    sessions: 90,
    interests: [
      "Pediatric Dentistry",
      "Fluoride Treatments",
      "Cavity Prevention",
    ],
    appointment: "Wednesday, Dec. 25 at 03:30 PM",
    topRated: true,
  },
  {
    name: "Dr. William Wilson",
    specialty: "Dentist",
    yearsOfExperience: 9,
    description: "Expert in periodontics.",
    rating: 4.7,
    sessions: 110,
    interests: ["Gum Diseases", "Dental Cleaning", "Plaque Management"],
    appointment: "Thursday, Dec. 26 at 04:45 PM",
    topRated: true,
  },
  {
    name: "Dr. Linda Martinez",
    specialty: "Dentist",
    yearsOfExperience: 11,
    description: "Specializes in endodontics.",
    rating: 4.8,
    sessions: 130,
    interests: ["Root Canal", "Dental Pain Relief", "Oral Health"],
    appointment: "Friday, Dec. 27 at 01:30 PM",
    topRated: true,
  },
  {
    name: "Dr. Robert Garcia",
    specialty: "Dentist",
    yearsOfExperience: 13,
    description: "Expert in prosthodontics.",
    rating: 4.9,
    sessions: 140,
    interests: ["Dental Crowns", "Dentures", "Smile Reconstruction"],
    appointment: "Saturday, Dec. 28 at 10:00 AM",
    topRated: true,
  },
  {
    name: "Dr. Angela White",
    specialty: "Orthodontist",
    yearsOfExperience: 10,
    description: "Specialist in braces and aligners.",
    rating: 4.5,
    sessions: 80,
    interests: ["Braces", "Clear Aligners", "Space Maintainers"],
    appointment: "Sunday, Dec. 29 at 11:30 AM",
    topRated: false,
  },
  {
    name: "Dr. Paul Adams",
    specialty: "Dentist",
    yearsOfExperience: 14,
    description: "Expert in prosthodontics and dental bridges.",
    rating: 4.6,
    sessions: 190,
    interests: ["Dental Bridges", "Dentures", "Tooth Restoration"],
    appointment: "Monday, Dec. 30 at 02:45 PM",
    topRated: false,
  },
  {
    name: "Dr. Anna Thompson",
    specialty: "Endodontist",
    yearsOfExperience: 9,
    description: "Focuses on root canals and oral pain management.",
    rating: 4.7,
    sessions: 115,
    interests: ["Root Canal", "Oral Pain Relief", "Tooth Preservation"],
    appointment: "Tuesday, Jan. 2 at 04:15 PM",
    topRated: true,
  },
  {
    name: "Dr. Steven Lee",
    specialty: "Periodontist",
    yearsOfExperience: 16,
    description: "Specialist in gum diseases and implants.",
    rating: 4.4,
    sessions: 170,
    interests: ["Gum Diseases", "Dental Implants", "Periodontal Surgery"],
    appointment: "Wednesday, Jan. 3 at 10:45 AM",
    topRated: false,
  },
  {
    name: "Dr. Julia Robinson",
    specialty: "Pediatric Dentist",
    yearsOfExperience: 6,
    description: "Loves working with children for healthy smiles.",
    rating: 4.8,
    sessions: 85,
    interests: ["Fluoride Treatments", "Cavity Prevention", "Sealants"],
    appointment: "Thursday, Jan. 4 at 01:45 PM",
    topRated: true,
  },
  {
    name: "Dr. Kevin Scott",
    specialty: "Dentist",
    yearsOfExperience: 8,
    description: "General dentist with focus on dental hygiene.",
    rating: 4.5,
    sessions: 95,
    interests: ["Dental Cleaning", "Cavity Fillings", "Oral Exams"],
    appointment: "Friday, Jan. 5 at 04:30 PM",
    topRated: false,
  },
  {
    name: "Dr. Olivia Harris",
    specialty: "Cosmetic Dentist",
    yearsOfExperience: 12,
    description: "Creating beautiful smiles with veneers and whitening.",
    rating: 4.9,
    sessions: 140,
    interests: ["Teeth Whitening", "Dental Veneers", "Smile Design"],
    appointment: "Saturday, Jan. 6 at 09:15 AM",
    topRated: true,
  },
];

export const doctorsInterests = [
  "Braces",
  "Cavity Fillings",
  "Cavity Prevention",
  "Clear Aligners",
  "Cosmetic Dentistry",
  "Dental Bonding",
  "Dental Bridges",
  "Dental Cleaning",
  "Dental Crowns",
  "Dental Implants",
  "Dental Pain Relief",
  "Dental Veneers",
  "Dentures",
  "Fluoride Treatments",
  "Gum Diseases",
  "Invisalign",
  "Jaw Alignment",
  "Oral Exams",
  "Oral Health",
  "Oral Pain Relief",
  "Oral Surgery",
  "Pediatric Dentistry",
  "Periodontal Surgery",
  "Plaque Management",
  "Root Canal",
  "Sealants",
  "Smile Design",
  "Smile Makeover",
  "Smile Reconstruction",
  "Space Maintainers",
  "Teeth Whitening",
  "Tooth Preservation",
  "Tooth Restoration",
  "Wisdom Teeth Removal",
];
