export const doctors = [
  {
    name: "Dr. John Doe",
    specialty: "Dentist",
    yearsOfExperience: 10,
    description: "Expert in dental implants.",
    rating: 4.8,
    sessions: 120,
    interests: ["Dental implants", "Teeth Whitening"],
    appointment: "Saturday, Dec. 21 at 09:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Jane Smith",
    specialty: "Dentist",
    yearsOfExperience: 8,
    description: "Specialist in cosmetic dentistry.",
    rating: 4.7,
    sessions: 100,
    interests: ["Cosmetic dentistry", "Teeth Whitening"],
    appointment: "Sunday, Dec. 22 at 10:00 AM",
    topRated: true,
  },
  {
    name: "Dr. Emily Johnson",
    specialty: "Dentist",
    yearsOfExperience: 12,
    description: "Specializes in orthodontics.",
    rating: 4.9,
    sessions: 150,
    interests: ["Braces", "Invisalign"],
    appointment: "Monday, Dec. 23 at 02:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Michael Brown",
    specialty: "Dentist",
    yearsOfExperience: 15,
    description: "Expert in oral surgery.",
    rating: 4.6,
    sessions: 200,
    interests: ["Oral surgery", "Wisdom Teeth Removal"],
    appointment: "Tuesday, Dec. 24 at 11:00 AM",
    topRated: false,
  },
  {
    name: "Dr. Sarah Davis",
    specialty: "Dentist",
    yearsOfExperience: 7,
    description: "Specialist in pediatric dentistry.",
    rating: 4.8,
    sessions: 90,
    interests: ["Pediatric Dentistry", "Fluoride Treatments"],
    appointment: "Wednesday, Dec. 25 at 03:00 PM",
    topRated: true,
  },
  {
    name: "Dr. William Wilson",
    specialty: "Dentist",
    yearsOfExperience: 9,
    description: "Expert in periodontics.",
    rating: 4.7,
    sessions: 110,
    interests: ["Gum Diseases", "Dental Cleaning"],
    appointment: "Thursday, Dec. 26 at 04:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Linda Martinez",
    specialty: "Dentist",
    yearsOfExperience: 11,
    description: "Specializes in endodontics.",
    rating: 4.8,
    sessions: 130,
    interests: ["Root Canal", "Dental Pain Relief"],
    appointment: "Friday, Dec. 27 at 01:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Robert Garcia",
    specialty: "Dentist",
    yearsOfExperience: 13,
    description: "Expert in prosthodontics.",
    rating: 4.9,
    sessions: 140,
    interests: ["Dental Crowns", "Dentures"],
    appointment: "Saturday, Dec. 28 at 09:30 AM",
    topRated: true,
  },
  {
    name: "Dr. Angela White",
    specialty: "Orthodontist",
    yearsOfExperience: 10,
    description: "Specialist in braces and aligners.",
    rating: 4.5,
    sessions: 80,
    interests: ["Braces", "Clear Aligners"],
    appointment: "Sunday, Dec. 29 at 10:00 AM",
    topRated: false,
  },
  {
    name: "Dr. Paul Adams",
    specialty: "Dentist",
    yearsOfExperience: 14,
    description: "Expert in prosthodontics and dental bridges.",
    rating: 4.6,
    sessions: 190,
    interests: ["Dental Bridges", "Dentures"],
    appointment: "Monday, Dec. 30 at 02:00 PM",
    topRated: false,
  },
  {
    name: "Dr. Anna Thompson",
    specialty: "Endodontist",
    yearsOfExperience: 9,
    description: "Focuses on root canals and oral pain management.",
    rating: 4.7,
    sessions: 115,
    interests: ["Root Canal", "Oral Pain Relief"],
    appointment: "Tuesday, Jan. 2 at 03:30 PM",
    topRated: true,
  },
  {
    name: "Dr. Steven Lee",
    specialty: "Periodontist",
    yearsOfExperience: 16,
    description: "Specialist in gum diseases and implants.",
    rating: 4.4,
    sessions: 170,
    interests: ["Gum Diseases", "Dental Implants"],
    appointment: "Wednesday, Jan. 3 at 11:00 AM",
    topRated: false,
  },
  {
    name: "Dr. Julia Robinson",
    specialty: "Pediatric Dentist",
    yearsOfExperience: 6,
    description: "Loves working with children for healthy smiles.",
    rating: 4.8,
    sessions: 85,
    interests: ["Fluoride Treatments", "Cavity Prevention"],
    appointment: "Thursday, Jan. 4 at 01:00 PM",
    topRated: true,
  },
  {
    name: "Dr. Kevin Scott",
    specialty: "Dentist",
    yearsOfExperience: 8,
    description: "General dentist with focus on dental hygiene.",
    rating: 4.5,
    sessions: 95,
    interests: ["Dental Cleaning", "Cavity Fillings"],
    appointment: "Friday, Jan. 5 at 04:00 PM",
    topRated: false,
  },
  {
    name: "Dr. Olivia Harris",
    specialty: "Cosmetic Dentist",
    yearsOfExperience: 12,
    description: "Creating beautiful smiles with veneers and whitening.",
    rating: 4.9,
    sessions: 140,
    interests: ["Teeth Whitening", "Dental Veneers"],
    appointment: "Saturday, Jan. 6 at 09:00 AM",
    topRated: true,
  },
];
